version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gosec
  settings:
    misspell:
      locale: US
    gosec:
      excludes:
        - G104

formatters:
  enable:
    - gofmt

output:
  formats:
    text:
      print-linter-name: true
