package appgateway

import (
	"context"
	"time"

	"github.com/base-14/metric-library/internal/adapter"
	"github.com/base-14/metric-library/internal/domain"
)

type Adapter struct{}

func NewAdapter(_ string) *Adapter {
	return &Adapter{}
}

func (a *Adapter) Name() string {
	return "azure-appgateway"
}

func (a *Adapter) SourceCategory() domain.SourceCategory {
	return domain.SourceCloud
}

func (a *Adapter) Confidence() domain.ConfidenceLevel {
	return domain.ConfidenceDocumented
}

func (a *Adapter) ExtractionMethod() domain.ExtractionMethod {
	return domain.ExtractionScrape
}

func (a *Adapter) RepoURL() string {
	return "https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-network-applicationgateways-metrics"
}

func (a *Adapter) Fetch(_ context.Context, _ adapter.FetchOptions) (*adapter.FetchResult, error) {
	return &adapter.FetchResult{
		Commit:    time.Now().Format("2006-01-02"),
		Timestamp: time.Now(),
	}, nil
}

func (a *Adapter) Extract(_ context.Context, _ *adapter.FetchResult) ([]*adapter.RawMetric, error) {
	var metrics []*adapter.RawMetric
	metrics = append(metrics, requestMetrics()...)
	metrics = append(metrics, connectionMetrics()...)
	metrics = append(metrics, healthMetrics()...)
	metrics = append(metrics, throughputMetrics()...)
	return metrics, nil
}

func requestMetrics() []*adapter.RawMetric {
	return []*adapter.RawMetric{
		{Name: "azure.appgateway.total_requests", Description: "Count of successful requests that Application Gateway has served", Unit: "1", InstrumentType: "counter", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.failed_requests", Description: "Count of failed requests that Application Gateway has served", Unit: "1", InstrumentType: "counter", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.response_status", Description: "Http response status returned by Application Gateway", Unit: "1", InstrumentType: "counter", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.backend_response_status", Description: "Number of HTTP response codes generated by the backend members", Unit: "1", InstrumentType: "counter", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.client_rtt", Description: "Average round trip time between clients and Application Gateway", Unit: "ms", InstrumentType: "gauge", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.application_gateway_total_time", Description: "Average time for a request to be processed and its response to be sent", Unit: "ms", InstrumentType: "gauge", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.backend_connect_time", Description: "Time spent establishing a connection with a backend server", Unit: "ms", InstrumentType: "gauge", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.backend_first_byte_response_time", Description: "Time interval between start of establishing a connection to backend server and receiving the first byte of the response header", Unit: "ms", InstrumentType: "gauge", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.backend_last_byte_response_time", Description: "Time interval between start of establishing a connection to backend server and receiving the last byte of the response body", Unit: "ms", InstrumentType: "gauge", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
	}
}

func connectionMetrics() []*adapter.RawMetric {
	return []*adapter.RawMetric{
		{Name: "azure.appgateway.current_connections", Description: "Count of current connections established with Application Gateway", Unit: "1", InstrumentType: "gauge", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.new_connections_per_second", Description: "New connections per second established with Application Gateway", Unit: "{connections}/s", InstrumentType: "gauge", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.rejected_connections", Description: "Count of rejected connections to Application Gateway", Unit: "1", InstrumentType: "counter", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
	}
}

func healthMetrics() []*adapter.RawMetric {
	return []*adapter.RawMetric{
		{Name: "azure.appgateway.healthy_host_count", Description: "Number of healthy backend hosts", Unit: "1", InstrumentType: "gauge", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.unhealthy_host_count", Description: "Number of unhealthy backend hosts", Unit: "1", InstrumentType: "gauge", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.backend_health_percentage", Description: "The percentage of healthy backends behind the application gateway", Unit: "%", InstrumentType: "gauge", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
	}
}

func throughputMetrics() []*adapter.RawMetric {
	return []*adapter.RawMetric{
		{Name: "azure.appgateway.throughput", Description: "Number of bytes per second the Application Gateway has served", Unit: "By/s", InstrumentType: "gauge", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.fixed_billable_capacity_units", Description: "Minimum capacity units that will be charged", Unit: "1", InstrumentType: "gauge", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.estimated_billed_capacity_units", Description: "Estimated capacity units that will be charged", Unit: "1", InstrumentType: "gauge", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.current_capacity", Description: "Current capacity of the Application Gateway", Unit: "1", InstrumentType: "gauge", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
		{Name: "azure.appgateway.compute_units", Description: "Compute units consumed", Unit: "1", InstrumentType: "gauge", ComponentName: "Application Gateway", ComponentType: "platform", SourceLocation: "Microsoft.Network/applicationGateways"},
	}
}
