.PHONY: dev build start lint test clean install

install:
	npm install

dev:
	npm run dev

build:
	npm run build

start:
	npm run start

lint:
	npm run lint

test:
	npm test

clean:
	rm -rf .next node_modules
